site_name: Kubernetes
site_description: Repositório do Projeto de Gerencia de Configuração e Evolução de Software
repo_url: https://github.com/gces-2022-1-kubernetes/wiki
dev_addr: '127.0.0.1:8000'
edit_uri: ""

theme:
    name: material
    logo: artifacts/Kubernetes_logo_without_workmark.png
    favicon: artifacts/fav-icon.png
    language: pt
    palette:
        primary: blue
    features:
        - navigation.tabs
plugins:
    - search